### ISSUE TITLE
todo for v0.9.3

### ISSUE THREAD

**Issue by kachmashk** [kachmashk/basketprotocol-flutter#104]
1.
   - [x] fix delete accounts
   - [x] summary tab for match page
   - [x] summary tab for contest page
2. anonymous user
   - [x] change settings page for anonymous user
   - [x] delete account except signing out
3. update previous stat after forcing next flushbar
   - [x] contest
      - [x] increment stat right with the click
      - [x] decrement with undo
      - [x] if the last stat of the zone was undone do not go to the next zone
      - [x] wait with changing a player
   - [x] match
      - [x] increment stat right with the click
      - [x] decrement with undo
